"""add audit columns

Revision ID: d74a0a6071a3
Revises: 5465da5c7aec
Create Date: 2026-07-29 18:38:27.336161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74a0a6071a3'
down_revision: Union[str, None] = '5465da5c7aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
